name: Deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone code on ubuntu-latest
        run: |
          echo "Cloning code on ubuntu-latest"
          echo "${{toJson(github)}}"
          git clone https://github.com/${{ github.repository }}.git

